# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_frontend', '0002_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='carrier',
            field=models.CharField(default='Sprint', max_length=40),
            preserve_default=False,
        ),
    ]
